<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LiteDB" />
      <PackageReference Include="Microsoft.Extensions.Hosting" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
      <PackageReference Include="Multifactor.Core.Ldap" />
      <PackageReference Include="Polly.Core" />
      <PackageReference Include="Polly.Extensions" />
      <PackageReference Include="Serilog.Expressions" />
      <PackageReference Include="Serilog.Extensions.Logging" />
      <PackageReference Include="Serilog.Settings.Configuration" />
      <PackageReference Include="Serilog.Sinks.Console" />
      <PackageReference Include="Serilog.Sinks.EventLog" />
      <PackageReference Include="Serilog.Sinks.File" />
      <PackageReference Include="System.DirectoryServices.Protocols" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DirectorySync.Application\DirectorySync.Application.csproj" />
      <ProjectReference Include="..\DirectorySync.Infrastructure.Shared\DirectorySync.Infrastructure.Shared.csproj" />
      <ProjectReference Include="..\DirectorySync.Shared\DirectorySync.Shared.csproj" />
    </ItemGroup>

</Project>
