<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CustomAction.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.Dtf.CustomAction" />
    <PackageReference Include="WixToolset.Dtf.WindowsInstaller" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/DirectorySync.Infrastructure.Shared/DirectorySync.Infrastructure.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
